### ISSUE TITLE
Port Setup

### ISSUE THREAD

**Issue by jiefool** [sharethrough/flare-up#20]
I'm currently using this gem to load data from s3 to redshift. It is working fine apart from the need to change the hardcoded port on lib/flare_up/connection.rb. It is using 5439 and in my redshift is 5943.  Adding port on the command options would be very awesome. Thank for this gem. You're awesome.

**Comment by russellcardullo** [comment]
Hi @jiefool!  Thanks for your feedback.  We just pushed a new version that includes the ability to set a port.  Let us know if that helps!
